<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>VulnDiag</RootNamespace>
    <AssemblyName>VulnDiag</AssemblyName>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetSecurityScanner\src\NetSecurityScanner.Core\NetSecurityScanner.Core.csproj" />
  </ItemGroup>
</Project>
