<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>NetSecurityScanner</RootNamespace>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <!-- <ApplicationIcon>Assets\netsec-icon.ico</ApplicationIcon> -->
    <NoWarn>$(NoWarn);NETSDK1138;NU1701;CS8600;CS8601;CS8602;CS8603;CS8604;CS8618;CS8625</NoWarn>
    <AssemblyVersion>1.0.2.2</AssemblyVersion>
    <FileVersion>1.0.2.2</FileVersion>
    <Version>1.0.2.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetSecurityScanner.Core\NetSecurityScanner.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.0" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.0" />
    <!-- 跨平台图表 -->
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.0.0-rc2" />
    <!-- 跨平台PDF生成 -->
    <PackageReference Include="QuestPDF" Version="2024.3.0" />
  </ItemGroup>

</Project>