<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Tools.PortVerify</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\NetSecurityScanner\src\NetSecurityScanner.Core\NetSecurityScanner.Core.csproj" />
  </ItemGroup>
</Project>
